# Generated by Django 2.2 on 2021-01-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweet',
            name='fechaDeRetweet',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fecha',
            field=models.CharField(max_length=128),
        ),
    ]
